# Generated by Django 3.0.3 on 2020-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_auto_20200215_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
