# Generated by Django 3.0.3 on 2020-02-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_auto_20200215_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start',
        ),
    ]
