# Generated by Django 3.0.3 on 2020-02-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_auto_20200215_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
